### ISSUE TITLE
xmr miner roblox and ransomware dont work

### ISSUE THREAD

**Issue by nuga0408** [rose-dll/Rose-Stealer#238]
**Describe the bug**
the xmr miner fails i dont get anything from roblox webcam and other almost everything dosent work with the ransomware it says it hit but the victim dosent see the ransomware
![Zrzut ekranu 2024-02-04 232402](https://github.com/rose-dll/Rose-Stealer/assets/158859265/b6591059-19f0-4cd6-b50b-1629f28a12cf)
)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gumbobr0t** [comment]
yeah because roblox is outdated, webcam, yes, obviously it wont work when you have no webcam or your cam is on a higher index than 0, ransomware works totally fine, i think you dont understand how it works. xmr miner obviously fails because windows defender removes it, consider enabling uac bypass > disable protectors...Am 04.02.24, 23:26 schrieb nuga0408 ***@***.***>:

   
  Describe the bug the xmr miner fails i dont get anything from roblox webcam and other almost everything dosent work with the ransomware it says it hit but the victim dosent see the ransomware A clear and concise description of what the bug is. Zrzut.ekranu.2024-02-04.232402.png (view on web) ) 
  To Reproduce Steps to reproduce the behavior: 
   
   Go to '...' 
   Click on '....' 
   Scroll down to '....' 
   See error 
   
  Expected behavior A clear and concise description of what you expected to happen. 
  Screenshots If applicable, add screenshots to help explain your problem. 
  Desktop (please complete the following information): 
   
   OS: [e.g. iOS] 
   Browser [e.g. chrome, safari] 
   Version [e.g. 22] 
   
  Smartphone (please complete the following information): 
   
   Device: [e.g. iPhone6] 
   OS: [e.g. iOS8.1] 
   Browser [e.g. stock browser, safari] 
   Version [e.g. 22] 
   
  Additional context Add any other context about the problem here.
